name: endothelial-maboss
channels:
  - conda-forge
  - defaults
  - colomoto
dependencies:
  - anyio=4.12.0=pyhcf101f3_0
  - aom=3.12.1=ha237518_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311h9408147_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.0=py311hca03da5_0
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyhcf101f3_1
  - babel=2.17.0=pyhd8ed1ab_0
  - backports.zstd=1.2.0=py311h97d6d38_0
  - beautifulsoup4=4.14.2=py311hca03da5_0
  - blas=1.0=openblas
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - boolean.py=4.0+git_1=py_0
  - bottleneck=1.4.2=py311h03d0aa3_1
  - brotli-python=1.2.0=py311hdc60ec4_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.12.2=hca03da5_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h191e429_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=1.17.1=py311h3a79f62_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cmaboss=1.0.0b31=py311h3447b82_0
  - colomoto_jupyter=0.9.2=py_0
  - comm=0.2.3=py311hca03da5_0
  - contourpy=1.3.3=py311h20e30b6_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.8.19=py311hc58e375_0
  - decorator=5.2.1=py311hca03da5_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - espresso-logic-minimizer=9999=h8a0c2ca_1
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=py311hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h29935d0_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.61.0=py311haa24f5a_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - gdk-pixbuf=2.42.10=h969f7ef_2
  - gettext=0.21.0=hbdbcc25_2
  - giflib=5.2.2=h80987f9_0
  - glib=2.84.4=h863a760_0
  - glib-tools=2.84.4=hff4a405_0
  - graphite2=1.3.14=hc377ac9_1
  - graphviz=2.50.0=hdc6c5f9_2
  - gts=0.7.6=hde733a8_3
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=10.2.0=he637ebf_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h313beb8_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.8.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=py311hca03da5_0
  - ipywidgets=8.1.7=py311hca03da5_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jansson=2.14=h80987f9_1
  - jedi=0.19.2=py311hca03da5_0
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.2=py311hca03da5_0
  - jpeg=9f=h2f69dba_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.5.1=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.15=py311hca03da5_0
  - kiwisolver=1.4.9=py311haeee614_0
  - krb5=1.21.3=h237132a_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.17=h7418793_0
  - lerc=4.0.0=h313beb8_0
  - libavif=1.3.0=h839b4eb_0
  - libboost=1.88.0=hb389264_0
  - libcurl=8.16.0=h01d3526_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h1a28f6b_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libgd=2.3.3=hd3b0a14_4
  - libgfortran5=15.2.0=hb654fa1_1
  - libglib=2.84.4=h7a3292d_0
  - libiconv=1.16=h80987f9_3
  - libidn2=2.3.8=h9681e36_0
  - libnghttp2=1.67.1=h8189af8_0
  - libopenblas=0.3.30=hf2bb037_2
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.50=h5c318fc_0
  - librsvg=2.56.3=h38920c8_2
  - libsbml-plus-packages=5.20.5=hceb19db_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.1=h9a5124b_0
  - libssh2=1.11.1=h3e2b118_0
  - libtiff=4.7.1=h367c460_0
  - libtool=2.4.7=h313beb8_0
  - libunistring=1.3=h1799b2a_0
  - libwebp=1.6.0=h30d73d9_0
  - libwebp-base=1.6.0=h92b2d59_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - maboss=2.6.5=h2263528_0
  - markupsafe=3.0.3=py311ha9b3269_0
  - matplotlib=3.10.7=py311hca03da5_0
  - matplotlib-base=3.10.7=py311haa222d5_0
  - matplotlib-inline=0.2.1=py311hca03da5_0
  - mistune=3.1.4=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.6.1=py311hca03da5_0
  - notebook=7.5.1=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - nspr=4.37=hd3a7ab8_0
  - nss=3.117=hfbaeeee_0
  - numexpr=2.14.1=py311h5fbe615_0
  - numpy=2.3.5=py311h4bb6f22_0
  - numpy-base=2.3.5=py311h23175f9_0
  - openjpeg=2.5.4=h959fc53_1
  - openssl=3.6.0=h5503f6c_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=py311hca03da5_1
  - pandas=2.3.3=py311hdb8e4fa_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.50.7=hf2328af_2
  - parso=0.8.5=py311hca03da5_0
  - pcre2=10.46=h1dacb4a_0
  - pexpect=4.9.0=py311hca03da5_1
  - pillow=12.0.0=py311he2d6fe4_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - poppler=24.09.0=h10a2f5c_4
  - poppler-data=0.4.12=hca03da5_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=py311hca03da5_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.1.3=py311h5bb9006_0
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py311hca03da5_0
  - pycparser=2.22=pyh29332c3_1
  - pydot=3.0.4=py311hca03da5_0
  - pygments=2.19.2=py311hca03da5_0
  - pygraphviz=1.14=py311h80987f9_1
  - pymaboss=0.8.12=py_0
  - pyobjc-core=11.0=py311hab620ed_0
  - pyobjc-framework-cocoa=11.0=py311hab620ed_0
  - pyparsing=3.2.5=py311hca03da5_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.11=h89a136b_0_cpython
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=py311hca03da5_0
  - pyyaml=6.0.3=py311ha9b3269_0
  - pyzmq=27.1.0=py311h13abfa4_0
  - readline=8.3=h0b18652_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.30.0=py311h71babbd_0
  - scikit-learn=1.7.2=py311h3f644e9_1
  - scipy=1.16.3=py311h08a1045_0
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=80.9.0=py311hca03da5_0
  - six=1.17.0=py311hca03da5_0
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.5=py311hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - stack_data=0.6.3=py311hca03da5_0
  - terminado=0.18.1=pyh31c8845_0
  - threadpoolctl=3.5.0=py311h7eb115d_1
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.15=hcd8a7d5_0
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.4=py311haa24f5a_0
  - traitlets=5.14.3=py311hca03da5_0
  - typing-extensions=4.15.0=py311hca03da5_0
  - typing_extensions=4.15.0=py311hca03da5_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h04d1e81_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.6.2=pyhd8ed1ab_0
  - wcwidth=0.2.13=py311hca03da5_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=py311hca03da5_0
  - widgetsnbextension=4.0.14=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h925e9cb_3
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
prefix: /opt/miniconda3/envs/endothelial-maboss
