# Metadata
experiment: "perturbation_simulation"

# Path Configuration
# Paths are relative to the PROJECT_ROOT
paths:
  model_bnd: "data/models/rho.bnd"
  model_cfg: "data/models/rho_v2.cfg"
  results_base: "results/boolean_models/final"
  figures_base: "figures/boolean_models"
  subdirs:
    param_sweep: "param_sweep"
    perturbation_sim: "perturbation_sim"
    perturbation_figs: "perturbation_figs"
    param_sweep_figs: "param_sweep_figs"
  

# Analysis Settings
analysis:
  nodes:
    target_a: "RhoA"
    target_b: "RhoC"
  eps: 0.25
  phenotypes:
    failed: "Failed"
    normal: "Normal"
    hyper: "Hyper"

# Perturbation Settings
perturbations:
  WT:  {}
  DSP: {DSP: "OFF"}
  TJP1: {TJP1: "OFF"}
  JCAD: {JCAD: "OFF"}
  DSP_JCAD: {DSP: "OFF", JCAD: "OFF"}
  TJP1_JCAD: {TJP1: "OFF", JCAD: "OFF"}
